<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.27">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Methodology – Oceanus Folk: Then and Now</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-ed96de9b727972fe78a7b5d16c58bf87.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-5b4ad623e5705c0698d39aec6f10cf02.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


<link rel="stylesheet" href="styles.css">
</head>

<body class="nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="./index.html">
    <span class="navbar-title">Oceanus Folk: Then and Now</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="./index.html"> 
<span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./proposal.html"> 
<span class="menu-text">Project Proposal</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link active" href="./methodology.html" aria-current="page"> 
<span class="menu-text">Methodology</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./writeup.html"> 
<span class="menu-text">Write-up</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./results.html"> 
<span class="menu-text">Results &amp; Discussion</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./poster.html"> 
<span class="menu-text">Poster</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./userguide.html"> 
<span class="menu-text">User Guide</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./about.html"> 
<span class="menu-text">About</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#overview" id="toc-overview" class="nav-link active" data-scroll-target="#overview">Overview</a></li>
  <li><a href="#data" id="toc-data" class="nav-link" data-scroll-target="#data">Data</a>
  <ul class="collapse">
  <li><a href="#source-dataset" id="toc-source-dataset" class="nav-link" data-scroll-target="#source-dataset">Source Dataset</a></li>
  <li><a href="#data-preparation" id="toc-data-preparation" class="nav-link" data-scroll-target="#data-preparation">Data Preparation</a></li>
  </ul></li>
  <li><a href="#tools" id="toc-tools" class="nav-link" data-scroll-target="#tools">Tools</a></li>
  <li><a href="#tableau-application" id="toc-tableau-application" class="nav-link" data-scroll-target="#tableau-application">Tableau Application</a>
  <ul class="collapse">
  <li><a href="#task-1-sailor-shift-career-profile" id="toc-task-1-sailor-shift-career-profile" class="nav-link" data-scroll-target="#task-1-sailor-shift-career-profile">Task 1 — Sailor Shift Career Profile</a></li>
  <li><a href="#task-2-oceanus-folk-genre-spread" id="toc-task-2-oceanus-folk-genre-spread" class="nav-link" data-scroll-target="#task-2-oceanus-folk-genre-spread">Task 2 — Oceanus Folk Genre Spread</a></li>
  <li><a href="#task-3-rising-star-prediction" id="toc-task-3-rising-star-prediction" class="nav-link" data-scroll-target="#task-3-rising-star-prediction">Task 3 — Rising Star Prediction</a></li>
  </ul></li>
  <li><a href="#python-visualisation-task-1-network-graphs" id="toc-python-visualisation-task-1-network-graphs" class="nav-link" data-scroll-target="#python-visualisation-task-1-network-graphs">Python Visualisation — Task 1 Network Graphs</a></li>
  <li><a href="#python-visualisation-task-2-sankey-diagram" id="toc-python-visualisation-task-2-sankey-diagram" class="nav-link" data-scroll-target="#python-visualisation-task-2-sankey-diagram">Python Visualisation — Task 2 Sankey Diagram</a></li>
  <li><a href="#python-visualisation-task-3-radar-chart" id="toc-python-visualisation-task-3-radar-chart" class="nav-link" data-scroll-target="#python-visualisation-task-3-radar-chart">Python Visualisation — Task 3 Radar Chart</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Methodology</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="overview" class="level2">
<h2 class="anchored" data-anchor-id="overview">Overview</h2>
<p>This project combines two deliverables — a Tableau application and this Quarto website — to address the three tasks of VAST Challenge 2025 Mini-Challenge 1. The raw source data (<code>MC1_graph.json</code>) was transformed into task-specific CSV files using a Python preprocessing pipeline (<code>Data/preprocess_mc1.py</code>), which were then loaded into Tableau for interactive dashboard construction; three supplementary chart types not natively supported by Tableau (network graphs, Sankey diagram, radar chart) were produced in Python and embedded in the website.</p>
</section>
<section id="data" class="level2">
<h2 class="anchored" data-anchor-id="data">Data</h2>
<section id="source-dataset" class="level3">
<h3 class="anchored" data-anchor-id="source-dataset">Source Dataset</h3>
<p>The source dataset is <code>MC1_graph.json</code>, a directed multigraph serialised in NetworkX <code>node_link_data</code> format. It represents the music industry in and around the fictional island nation of Oceanus from 1993 to 2040.</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Dimension</th>
<th style="text-align: right;">Count</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Nodes</td>
<td style="text-align: right;">17,412</td>
</tr>
<tr class="even">
<td>Edges</td>
<td style="text-align: right;">37,857</td>
</tr>
<tr class="odd">
<td>Connected components</td>
<td style="text-align: right;">18</td>
</tr>
</tbody>
</table>
<p><strong>Node types (5):</strong></p>
<table class="caption-top table">
<colgroup>
<col style="width: 24%">
<col style="width: 28%">
<col style="width: 48%">
</colgroup>
<thead>
<tr class="header">
<th>Type</th>
<th style="text-align: right;">Count</th>
<th>Key Fields</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Person</td>
<td style="text-align: right;">11,361</td>
<td><code>name</code>, <code>stage_name</code></td>
</tr>
<tr class="even">
<td>Song</td>
<td style="text-align: right;">3,615</td>
<td><code>name</code>, <code>genre</code>, <code>release_date</code>, <code>written_date</code>, <code>single</code>, <code>notable</code>, <code>notoriety_date</code></td>
</tr>
<tr class="odd">
<td>RecordLabel</td>
<td style="text-align: right;">1,217</td>
<td><code>name</code></td>
</tr>
<tr class="even">
<td>Album</td>
<td style="text-align: right;">996</td>
<td><code>name</code>, <code>genre</code>, <code>release_date</code>, <code>written_date</code>, <code>notable</code>, <code>notoriety_date</code></td>
</tr>
<tr class="odd">
<td>MusicalGroup</td>
<td style="text-align: right;">223</td>
<td><code>name</code></td>
</tr>
</tbody>
</table>
<p><strong>Edge types (12):</strong></p>
<table class="caption-top table">
<colgroup>
<col style="width: 27%">
<col style="width: 31%">
<col style="width: 40%">
</colgroup>
<thead>
<tr class="header">
<th>Type</th>
<th style="text-align: right;">Count</th>
<th>Meaning</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>PerformerOf</td>
<td style="text-align: right;">13,587</td>
<td>Person/Group performed Song/Album</td>
</tr>
<tr class="even">
<td>RecordedBy</td>
<td style="text-align: right;">3,798</td>
<td>Song/Album recorded by RecordLabel</td>
</tr>
<tr class="odd">
<td>ComposerOf</td>
<td style="text-align: right;">3,290</td>
<td>Person composed Song/Album</td>
</tr>
<tr class="even">
<td>ProducerOf</td>
<td style="text-align: right;">3,209</td>
<td>Person/Label produced Song/Album/Person/Group</td>
</tr>
<tr class="odd">
<td>DistributedBy</td>
<td style="text-align: right;">3,013</td>
<td>Song/Album distributed by RecordLabel</td>
</tr>
<tr class="even">
<td>LyricistOf</td>
<td style="text-align: right;">2,985</td>
<td>Person wrote lyrics for Song/Album</td>
</tr>
<tr class="odd">
<td>InStyleOf</td>
<td style="text-align: right;">2,289</td>
<td>Song/Album made in style of another Song/Album/Person/Group</td>
</tr>
<tr class="even">
<td>InterpolatesFrom</td>
<td style="text-align: right;">1,574</td>
<td>Song/Album interpolated melody from another</td>
</tr>
<tr class="odd">
<td>LyricalReferenceTo</td>
<td style="text-align: right;">1,496</td>
<td>Song/Album makes lyrical reference to another</td>
</tr>
<tr class="even">
<td>CoverOf</td>
<td style="text-align: right;">1,429</td>
<td>Song/Album is a cover of another</td>
</tr>
<tr class="odd">
<td>DirectlySamples</td>
<td style="text-align: right;">619</td>
<td>Song/Album directly samples audio from another</td>
</tr>
<tr class="even">
<td>MemberOf</td>
<td style="text-align: right;">568</td>
<td>Person is/was member of MusicalGroup</td>
</tr>
</tbody>
</table>
<p>Two fields are critical for the analysis. The boolean <code>notable</code> records whether a song or album appeared on a top chart. The string field <code>notoriety_date</code> records the year of that first chart appearance. Together these allow reconstruction of each artist’s breakthrough trajectory across 649 charted works.</p>
</section>
<section id="data-preparation" class="level3">
<h3 class="anchored" data-anchor-id="data-preparation">Data Preparation</h3>
<p>A single Python script (<code>Data/preprocess_mc1.py</code>) transforms the raw node and edge CSVs into 14 task-specific files stored in <code>Data/mc1_csv/processed/</code>. The script begins by loading <code>mc1_nodes.csv</code> (17,412 rows) and <code>mc1_edges.csv</code> (37,857 rows) and applying a uniform cleaning pass: <code>notable</code> and <code>single</code> fields have NaN values filled as <code>False</code> and are cast to boolean; <code>release_date</code>, <code>notoriety_date</code>, and <code>written_date</code> are converted from float to integer-year strings with missing values stored as empty strings; <code>genre</code> is filled as <code>"Unknown"</code> where missing; <code>stage_name</code> is filled as empty string; <code>name</code> is whitespace-stripped; and all ID columns (<code>id</code>, <code>source</code>, <code>target</code>) are cast to integer for reliable merge keys. Twelve edge types are partitioned into two semantic groups used throughout the pipeline: five <em>influence</em> types (<code>InStyleOf</code>, <code>InterpolatesFrom</code>, <code>CoverOf</code>, <code>DirectlySamples</code>, <code>LyricalReferenceTo</code>) and four <em>collaboration</em> types (<code>PerformerOf</code>, <code>ComposerOf</code>, <code>LyricistOf</code>, <code>ProducerOf</code>). A helper function computes each artist’s <em>main genre</em> as the most frequent genre among all works they are connected to via collaboration edges; this derived attribute is reused across multiple output files.</p>
<p>For Task 1, the script identifies Sailor Shift by node ID 17255 and her Ivy Echoes bandmates by IDs 17256–17259 (Maya Jensen, Lila Hartman, Jade Thompson, Sophie Ramirez), with the Ivy Echoes group entity at ID 17260. <code>task1_a_who_inspired_sailor.csv</code> (30 rows) captures all influence edges originating from Sailor’s 38 works and from Sailor as a person, with targets representing the songs, albums, or groups that inspired her; edge type codes are mapped to human-readable names (e.g.&nbsp;<code>InStyleOf</code> → <code>Inspired by Style</code>) and a <code>Source Is Person</code> flag distinguishes whether the influence link originated from a specific work or from Sailor directly. <code>task1_b_sailor_collaborations.csv</code> (126 rows) collects every collaboration edge on Sailor’s 38 works — not just Sailor’s own edges but all persons and groups who performed, composed, wrote lyrics for, or produced those works — enriched with each person’s computed main genre and binary flags for Ivy Echoes membership and Sailor identity. <code>task1_c_oceanus_impact_timeline.csv</code> (215 rows) focuses on Sailor’s local Oceanus Folk network: it takes a curated set of 81 OF works connected to Sailor’s circle, identifies all artists on those works whose main genre falls within the OF-related family (Oceanus Folk, Celtic Folk, Sea Shanties, Acoustic Folk), and labels each collaboration with an <code>Era</code> column based on whether the work was released before, during, or after Sailor’s breakthrough year of 2028. All three Task 1 files are saved as UTF-16 tab-separated CSVs to match the format expected by the existing Tableau workbook.</p>
<p>For Task 2, the script collects all Oceanus Folk song and album node IDs, then extracts two directional influence sets. <code>task2_of_influence_out.csv</code> (371 rows) captures all influence edges where the source is an OF work, joined with source and target node metadata (name, genre, release date, notable status, notoriety date). <code>task2_of_influence_in.csv</code> (377 rows) captures the reverse — influence edges where the target is an OF work. <code>task2_genre_summary.csv</code> (117 rows) aggregates both sets by <code>(source_genre, target_genre, edge_type)</code> with a <code>direction</code> column (<code>outbound</code> or <code>inbound</code>), excluding internal OF-to-OF flows. <code>task2_top_artists_influenced.csv</code> (30 rows) traces <code>PerformerOf</code> edges from the non-OF works that appear as targets in the outbound influence set back to their performing artists, aggregates per artist the count of influenced works and notable works among them, assigns a primary genre based on the most frequent genre among the artist’s influenced works, and exports the top 30 artists ranked by influenced work count.</p>
<p>For Task 3, <code>task3_notable_works.csv</code> (1,973 rows) filters all nodes where <code>notable = True</code> and <code>notoriety_date</code> is not empty, then joins <code>PerformerOf</code> edges to associate each charted work with its performing artist. <code>task3_artist_notoriety.csv</code> (1,664 rows) aggregates to one row per performer with four summary metrics — <code>total_notable_works</code>, <code>first_notoriety_date</code>, <code>latest_notoriety_date</code>, and <code>years_active_span</code> (difference between earliest and latest release dates) — plus a comma-separated <code>genres</code> field and a boolean <code>is_oceanus_folk_artist</code> flag set to True if any of the artist’s notable works are Oceanus Folk. <code>task3_of_candidates.csv</code> (84 rows) filters to OF artists only and joins the four summary metrics from the notoriety table, enabling both work-level and artist-level analysis within a single Tableau data source.</p>
<p>Finally, two shared lookup files are produced: <code>lookup_nodes_clean.csv</code> (17,412 rows) exports the full cleaned node table, and <code>lookup_edges_clean.csv</code> (37,857 rows) exports the full edge table enriched with source and target node names and types. Two additional files — <code>nodes.csv</code> (193 rows) and <code>edges.csv</code> (340 rows) — provide a curated subgraph of Sailor Shift’s local network used as input by the Python network visualisation scripts; nodes are classified into roles (Sailor Shift, Ivy Echoes Member, Direct Collaborator, Sailor Work, Inspired Sailor, Inspired By Sailor Circle) and edges carry an <code>edge_category</code> label and involvement flags.</p>
</section>
</section>
<section id="tools" class="level2">
<h2 class="anchored" data-anchor-id="tools">Tools</h2>
<p><strong>Tableau</strong> handles all standard chart types: horizontal and stacked bar charts, scatter plots, dot plots, line charts, and highlight tables. Every interactive dashboard was built in Tableau and exported as a combined <code>.twbx</code> workbook. All CSV files were loaded as separate data connections within a single workbook — no cross-source joins or unions were performed to avoid row multiplication and direction mixing. Each sheet uses only one data source at a time.</p>
<p><strong>Python</strong> was used for three chart types that Tableau does not natively support:</p>
<ul>
<li><strong>Network graphs</strong> (Task 1): Built using <code>pyvis</code> (a Python wrapper around vis.js). Two interactive HTML network visualisations — a collaboration network and an influence network — were generated and embedded in the Quarto website via <code>&lt;iframe&gt;</code> elements. Pyvis was selected because it produces self-contained HTML files with built-in pan, zoom, and hover interactions, which can be embedded directly in a static website without a server backend.</li>
<li><strong>Sankey diagram</strong> (Task 2): Built using <code>plotly</code> to show bidirectional genre influence flows. Plotly’s Sankey trace type was selected because it handles variable-width flow bands with hover tooltips and node repositioning out of the box. The output was saved as both interactive HTML and a static PNG for embedding.</li>
<li><strong>Radar chart</strong> (Task 3): Built using <code>matplotlib</code> to compare five normalised metrics across the top five Oceanus Folk candidates simultaneously. Matplotlib’s polar projection was used because it provides precise control over grid lines, label positioning, and overlapping polygon fills — features that Plotly’s Scatterpolar lacks at equivalent visual polish. The output was saved as a static PNG at 150 dpi and embedded as an image in the Tableau dashboard.</li>
</ul>
<p><strong>Quarto + Vercel</strong> powers this website. Source files are <code>.qmd</code> documents rendered to HTML by Quarto and auto-deployed to production on every push to the <code>main</code> branch via Vercel.</p>
</section>
<section id="tableau-application" class="level2">
<h2 class="anchored" data-anchor-id="tableau-application">Tableau Application</h2>
<p>The combined <code>.twbx</code> workbook contains 15 worksheets grouped across the three tasks. Field names below are translated from the internal Tableau federated IDs to human-readable names.</p>
<section id="task-1-sailor-shift-career-profile" class="level3">
<h3 class="anchored" data-anchor-id="task-1-sailor-shift-career-profile">Task 1 — Sailor Shift Career Profile</h3>
<table class="caption-top table">
<colgroup>
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
</colgroup>
<thead>
<tr class="header">
<th>Worksheet</th>
<th>Mark Type</th>
<th>Rows</th>
<th>Columns</th>
<th>Key Filters</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Collaborations Over Time</td>
<td>Square</td>
<td>Person Name</td>
<td>Work Release Year</td>
<td>Is Ivy Member, Person Name</td>
</tr>
<tr class="even">
<td>Genre Influences Over Time</td>
<td>Circle</td>
<td>Inspiration Genre</td>
<td>Sailor Work Release Year</td>
<td>Sailor Work Release Year</td>
</tr>
<tr class="odd">
<td>Direct &amp; Indirect Influence</td>
<td>Bar</td>
<td>Influenced Entity Name</td>
<td>Count of Influenced Entity ID</td>
<td>—</td>
</tr>
<tr class="even">
<td>OF Production Over Time</td>
<td>Bar</td>
<td>Count of Work ID</td>
<td>Work Release Year</td>
<td>—</td>
</tr>
<tr class="odd">
<td>Top Contributors After 2028</td>
<td>Bar</td>
<td>Artist Name</td>
<td>Count of Work ID</td>
<td>Artist Name, Era</td>
</tr>
</tbody>
</table>
<p>Dashboard 1 combines Collaborations Over Time (top), Genre Influences Over Time (bottom-left), and Direct &amp; Indirect Influence (bottom-right). Dashboard 2 combines OF Production Over Time (left) and Top Contributors After 2028 (right).</p>
</section>
<section id="task-2-oceanus-folk-genre-spread" class="level3">
<h3 class="anchored" data-anchor-id="task-2-oceanus-folk-genre-spread">Task 2 — Oceanus Folk Genre Spread</h3>
<table class="caption-top table">
<colgroup>
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
</colgroup>
<thead>
<tr class="header">
<th>Worksheet</th>
<th>Mark Type</th>
<th>Rows</th>
<th>Columns</th>
<th>Key Filters</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Outbound Genre Influence</td>
<td>Bar</td>
<td>Target Genre</td>
<td>Sum of Connection Count</td>
<td>Direction = outbound, Target Genre ≠ Oceanus Folk</td>
</tr>
<tr class="even">
<td>Inbound Genre Influence</td>
<td>Bar</td>
<td>Source Genre</td>
<td>Sum of Connection Count</td>
<td>Direction = inbound, Source Genre ≠ Oceanus Folk</td>
</tr>
<tr class="odd">
<td>Outward Influence Trend</td>
<td>Line</td>
<td>Count of Source Name</td>
<td>Source Release Date</td>
<td>Target Genre ≠ Oceanus Folk</td>
</tr>
<tr class="even">
<td>Inward Influence Trend</td>
<td>Line</td>
<td>Count of Source Name</td>
<td>Source Release Date</td>
<td>Source Genre ≠ Oceanus Folk</td>
</tr>
<tr class="odd">
<td>Influenced Artists</td>
<td>Bar</td>
<td>Artist Name</td>
<td>Sum of Influenced Works Count</td>
<td>Top 15 by Artist Name</td>
</tr>
</tbody>
</table>
<p>Dashboard 1 places Outbound Genre Influence and Inbound Genre Influence side by side. Dashboard 2 stacks Outward Influence Trend and Inward Influence Trend vertically, both annotated at 2023 and 2028 with Sailor’s career milestones. Dashboard 3 shows Influenced Artists alone.</p>
</section>
<section id="task-3-rising-star-prediction" class="level3">
<h3 class="anchored" data-anchor-id="task-3-rising-star-prediction">Task 3 — Rising Star Prediction</h3>
<table class="caption-top table">
<colgroup>
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
</colgroup>
<thead>
<tr class="header">
<th>Worksheet</th>
<th>Mark Type</th>
<th>Rows</th>
<th>Columns</th>
<th>Key Filters</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Oceanus Folk Artist Ranking</td>
<td>Bar</td>
<td>Performer Name</td>
<td>Sum of Total Notable Works</td>
<td>Is Oceanus Folk Artist = True, Sum ≥ 2</td>
</tr>
<tr class="even">
<td>Genre Mix by Candidate</td>
<td>Bar</td>
<td>Artist Name</td>
<td>Count of Work Name</td>
<td>Top 5 by Count of Work Name</td>
</tr>
<tr class="odd">
<td>Notoriety Timeline</td>
<td>Circle</td>
<td>Artist Name</td>
<td>Notoriety Date</td>
<td>Sum of Total Notable Works ≥ 2</td>
</tr>
<tr class="even">
<td>Three Artist Comparison</td>
<td>Circle</td>
<td>Artist Name / Work Name</td>
<td>Notoriety Date</td>
<td>Artist Name = 3 selected stars</td>
</tr>
<tr class="odd">
<td>Breakthrough Profile</td>
<td>Circle</td>
<td>Sum of Total Notable Works</td>
<td>Years Active Span</td>
<td>Is Oceanus Folk Artist = True, Sum ≥ 2</td>
</tr>
</tbody>
</table>
<p>Dashboard 1 (“Who are the Candidates?”) tiles Oceanus Folk Artist Ranking (top-left), Genre Mix by Candidate (top-right), and Breakthrough Profile (bottom, full width). Dashboard 2 (“Who’s Next?”) tiles Three Artist Comparison (top-left), Notoriety Timeline (bottom-left), and the Python-generated radar chart PNG (right panel).</p>
</section>
</section>
<section id="python-visualisation-task-1-network-graphs" class="level2">
<h2 class="anchored" data-anchor-id="python-visualisation-task-1-network-graphs">Python Visualisation — Task 1 Network Graphs</h2>
<p>Two interactive network graphs were generated using <code>pyvis</code> (Python) and embedded in the Quarto website as HTML <code>&lt;iframe&gt;</code> elements.</p>
<p><strong>Collaboration Network</strong> (<code>Data/task1_network_collaboration.py</code>): The script loads the processed node and edge CSVs, identifies all Person nodes with roles “Sailor Shift”, “Direct Collaborator”, or “Ivy Echoes Member”, then constructs derived edges by finding collaborators who share work nodes with Sailor. For each collaborator, the edge types (e.g.&nbsp;<code>PerformerOf</code>, <code>ComposerOf</code>) are aggregated into a tooltip. The network uses a ForceAtlas2 physics layout with gravitational constant −80, spring length 120, and 250 stabilisation iterations. Node colours distinguish Sailor (gold, size 40), Ivy Echoes members (emerald green, size 25), and other collaborators (blue, size 20). A fixed title bar and colour legend were injected into the output HTML.</p>
<p><strong>Influence Network</strong> (<code>Data/task1_network_influence.py</code>): The script includes six node roles: Sailor Shift, Sailor’s works, direct collaborators, Ivy Echoes members, artists inspired by Sailor, and artists inspired by Sailor’s circle. Directed edges preserve the original edge types. The layout uses ForceAtlas2 with gravitational constant −60, spring length 150, and 300 stabilisation iterations. Sailor is rendered as a gold star (size 50), her works as orange dots, collaborators as blue dots, Ivy Echoes members as green dots, and inspired artists as purple dots.</p>
</section>
<section id="python-visualisation-task-2-sankey-diagram" class="level2">
<h2 class="anchored" data-anchor-id="python-visualisation-task-2-sankey-diagram">Python Visualisation — Task 2 Sankey Diagram</h2>
<p>A bidirectional Sankey diagram was generated using <code>plotly</code> to show the flow of influence between Oceanus Folk and other genres simultaneously. The script loads <code>task2_genre_summary.csv</code>, removes internal Oceanus Folk flows and connections with fewer than 3 occurrences, then creates two virtual anchor nodes: “Oceanus Folk → Outward” (left, blue) and “Inward → Oceanus Folk” (right, purple). Genre nodes are positioned between the anchors and colour-coded: orange for bidirectional genres (those appearing on both outbound and inbound sides), light blue for outbound-only, and red/pink for inbound-only. The output was saved as both an interactive HTML file and a static PNG.</p>
</section>
<section id="python-visualisation-task-3-radar-chart" class="level2">
<h2 class="anchored" data-anchor-id="python-visualisation-task-3-radar-chart">Python Visualisation — Task 3 Radar Chart</h2>
<p>A radar chart (<code>Data/task3_radar.py</code>) compares the top five Oceanus Folk candidates across five normalised dimensions. The script loads <code>task3_artist_notoriety.csv</code>, filters to Oceanus Folk artists, selects the top five by <code>total_notable_works</code>, and computes a genre diversity count from the comma-separated <code>genres</code> field.</p>
<p>Five metrics are defined and min–max normalised within the five-candidate pool:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 25%">
<col style="width: 40%">
<col style="width: 34%">
</colgroup>
<thead>
<tr class="header">
<th>Metric</th>
<th>Source Field</th>
<th>Direction</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Total Notable Works</td>
<td><code>total_notable_works</code></td>
<td>Higher = better</td>
</tr>
<tr class="even">
<td>Quick Breakthrough</td>
<td><code>years_active_span</code> (inverted)</td>
<td>Lower span = higher score</td>
</tr>
<tr class="odd">
<td>Early Breakthrough</td>
<td><code>first_notoriety_date</code> (inverted)</td>
<td>Earlier year = higher score</td>
</tr>
<tr class="even">
<td>Recent Activity</td>
<td><code>latest_notoriety_date</code></td>
<td>Later year = higher score</td>
</tr>
<tr class="odd">
<td>Genre Diversity</td>
<td>Count of unique genres in <code>genres</code></td>
<td>More genres = higher score</td>
</tr>
</tbody>
</table>
<p>Normalisation is scoped to the five-candidate pool rather than the full dataset, so each radar axis represents relative standing among the top candidates only. The chart uses matplotlib’s polar projection with a white background, five concentric grid rings (0.25, 0.50, 0.75, 1.00), spoke lines, and semi-transparent filled polygons for each artist. A companion data table showing raw values is rendered alongside the radar using matplotlib’s table function. Specific colours were assigned to each artist for consistency with the Tableau dashboards. The figure was saved at 150 dpi as a PNG and embedded in the Tableau workbook as a static image.</p>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>